### ISSUE TITLE
Add several devDependencies for React application with Swagger and GraphiQL over a REST API

### ISSUE THREAD

**Issue by nhpatt** [liferay/liferay-frontend-guidelines#156]
## What is the new or updated dependency?

-- Several (I can create a ticket for each one) if you prefer.

- [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) to create/modify html files.
- [script-ext-html-webpack-plugin](https://www.npmjs.com/package/script-ext-html-webpack-plugin) to inline scripts
- [mini-css-extract-plugin](https://www.npmjs.com/package/mini-css-extract-plugin) to extract CSS
- [style-ext-html-webpack-plugin](https://www.npmjs.com/package/style-ext-html-webpack-plugin) to inline CSS

```
"html-webpack-plugin": "4.3.0",
"script-ext-html-webpack-plugin": "2.1.1",
"style-ext-html-webpack-plugin": "4.1.2",
"mini-css-extract-plugin": "0.9.0"
```

## Why is this dependency useful to you and others?

I want to serve a bundled html with SwaggerUI & GraphiQL over a REST API, a documentation page listing the APIs/endpoints. These dependencies inline HTML & CSS to be able to create a bundled html with all the dependencies.

`html-webpack-plugin` is a "standard" webpack plugin, the other 3 are [plugins](https://github.com/jantimon/html-webpack-plugin#plugins) using the hooks available.

I don't think they are useful for a general case inside the portal, l think they make more sense as part of a webpack preset.

## What are the alternatives?

- Other alternatives discussed here: https://github.com/liferay/liferay-frontend-guidelines/issues/155 (use the bundler 3, don't integrate...)
- Serve the css/js over the API, basically recreating a web server (that would avoid requiring inlining the css/JS).

**Comment by izaera** [comment]
> I don't think they are useful for a general case inside the portal, l
> think they make more sense as part of a webpack preset.

Once we start using bundler 3 in every project we will need webpack
plugins to do all the stuff so it's probable that we end up needing
some or all of these plugins.

**Comment by wincent** [comment]
> -- Several (I can create a ticket for each one) if you prefer.

Nah, all in one is fine.

Let's leave this open for a bit to give people who may have had experience with these plug-ins a chance to see/comment. (My understanding is that you're not currently blocked on this, seeing as you have a local `devDependencies` lint suppression; is that right @nhpatt? — In general we like to hold things open for an interval for a comment so that we don't wind up being on the hook to support a dependency that we might have pushed back on if we'd held it for review a little longer.)

In terms of general cost/benefit/risk analysis for these; some stats, from least to most sketchy:

- https://github.com/webpack-contrib/mini-css-extract-plugin
  - 7.8m weekly downloads
  - 3.9k GitHub stars
  - 59 open issues
  - 26 open (non-bot) PRs
  - Last commit: Dec 2019
  - Last release: Dec 2019
  - 4 top-level items in dependency graph.
- https://github.com/numical/script-ext-html-webpack-plugin
  - 123k weekly downloads
  - 497 GitHub stars
  - 15 open issues
  - 1 open (non-bot) PR
  - Last commit: July 2019
  - Last tagged release: Nov 2018; last non-tagged release: July 2019
  - 1 top-level item in dependency graph.
- https://github.com/numical/style-ext-html-webpack-plugin
  - 33k weekly downloads
  - 120 GitHub stars
  - 6 open issues
  - 0 open (non-bot) PRs
  - Last commit: July 2019
  - Last tagged release: Jan 2018; last non-tagged release: July 2019
  - 2 top-level items in dependency graph.

No glaring red flags there, I guess.

**Comment by nhpatt** [comment]
I'm not in a hurry :) (but I don't have a local devDependencies lint suppression either, that PR was reverted and I passed one without devDependencies)

**Comment by wincent** [comment]
Closing this via:

- https://github.com/liferay/liferay-npm-tools/pull/457 →
- https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-scripts%2Fv32.3.0 →
- https://issues.liferay.com/browse/LPS-114785 →
- https://github.com/wincent/liferay-portal/pull/308 →
- ...

**Comment by nhpatt** [comment]
Thank you so much! :)

**Comment by wincent** [comment]
> In terms of general cost/benefit/risk analysis for these; some stats, from least to most sketchy:
> 
> * https://github.com/numical/script-ext-html-webpack-plugin
>   * Last tagged release: Nov 2018; last non-tagged release: July 2019 ([issue](https://github.com/numical/script-ext-html-webpack-plugin/issues/76))

This one is [officially unmaintained now](https://github.com/numical/script-ext-html-webpack-plugin/issues/76#issuecomment-716731185) and [won't work with webpack 5](https://github.com/numical/script-ext-html-webpack-plugin/blob/master/README.md) so we will eventually need to find a replacement for it; the same will be true for the other numical plugin, I expect.
