### ISSUE TITLE
Could we explains or clarify the movement of the styles from themes to content pages?

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-guidelines#187]
I'm not sure if this is our responsibility or we actually need more information about the general roadmap but I think is pretty necessary for the team (or only me) the movement of the styles from themes to content pages

Content pages are great but most current Liferay portal customers and integrators are too used to 'the old way' of doing things in Liferay, so I think can be an interesting rethink about:

- The current state of themes and content pages
- The Liferay's vision for themes
   - Are we killing themes?
   - Are we killing widget pages in favor of content pages?
- How they work together
- How Clay CSS is playing along with this new concept

In order to for example create new and more powerful proposals, for example:

## If the intention is to deprecate themes as the main style provider:

- We could work on a way to moving clay CSS framework to the content pages, for example as a collection level
- We could move content page configurations to the content page level, for example:
   - `<setting configurable="false" key="color-palette" value="primary,success,danger,warning,info,dark,gray-dark,secondary,light,lighter,white" />` in `look-and-feel.xml`
   - All token definitions
- Work on two themes:
   - A theme only with widgets and Liferay essentials styles (if you use widgets or Liferay old dependencies).
      - A new type of base theme, called (for example) `minStyled`:-P
   - A complete unstyled theme
      - By using `unstyled` theme or even not use a theme (we would need an alternative place to allocate the basic structure page (`.ftl` files).
   - Work on a site, not bootstrap based (currently technical possible if we improve the jump between live and edit mode)

## If the intention is to make themes and content pages styles work together for a long time:

- Work on improving the flow of combining that two mechanisms by:
   - Improve labeling
   - Probably improving the inheritance of styles, for example:
      - More references in editing time to Theme/Frameworks
      - Improve critical theme styles that need a theme compilation (move them?)
   - Create better public documentation

Some of the previous points probably would need its own `Issue` type `Proposal`

**Comment by jbalsas** [comment]
> Could we explains or clarify the movement of the styles from themes to content pages?

So, this is mostly a Product decision that would certainly impact how our roadmap as a team (Frontend Infra) looks like. We should be seeing more of this internally in the next weeks and plan next steps accordingly. Product is looking to solidify this position throughout September so I'll keep the team updated as soon as things are more clear.

The answer, as usual, is more nuanced than _deprecate themes as the main style provider_ or _make themes and content pages styles work together for a long time_ and it will probably be something in between.

> Some of the previous points probably would need its own Issue type Proposal

As I said, my idea would be:
- Show the team the concepts so we can build the roadmap throughout September
- Finalize product decisions by the end of the month so we can start working on ideas

I know this doesn't answer exactly the question, but this does not feel the channel to evolve this.

One thing that would be benefitial in any case, in preparation, would be to document the current architecture of theming, widgets, contributors, content pages... so that we can use that knowledge and information in the near future 😉

**Comment by marcoscv-work** [comment]
Thank you so much @jbalsas !

We already have a lot of documentation about theming, not sure about content pages.. but yes, we do not have documentation from a perspective of everything working together, so probably it could be giving us a new perspective.
