### ISSUE TITLE
Document how the npmbundler's imports mechanism works

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-guidelines#189]
This arose as a [question in Slack](https://liferay.slack.com/archives/G3JBR21HA/p1598992144297600), but I think it's worth documenting it somewhere.

Maybe the correct place would be the [liferay-js-toolkit repo](https://github.com/liferay/liferay-js-toolkit) so it is possible that I end up writing it there and linking it from here. Any opinions on this? :thinking:

**Comment by jbalsas** [comment]
> Maybe the correct place would be the liferay-js-toolkit repo so it is possible that I end up writing it there and linking it from here. Any opinions on this? 🤔

Let's start here

**Comment by wincent** [comment]
One of the nice things about writing it here is you can write it for exactly one audience (ie. Liferay internal developers) instead of two (ie. internal devs + external devs reading the wiki). It might be that you would want to say the same things to both groups, but in the event that you don't, writing it for a single audience is easier for you and more valuable for that audience too.
