### ISSUE TITLE
Document when to use Liferay.publish, Liferay.provide and Liferay.<myCustomFunctionallity/Property>

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-guidelines#192]
## What is your question?

There are three ways to expose a thing on global `Liferay` object, where I don't know for sure when to use a method or not

**Comment by wincent** [comment]
I don't recall what `Liferay.publish` does, but about the other two:

- You should never use `Liferay.provide` (it's AUI and we've actually done a lot of work removing usages; for example, look at the "Avoid Liferay.provide" tasks in [LPS-115885](https://issues.liferay.com/browse/LPS-115885)).
- You should only stick things on the `Liferay` global as a last resort; instead, encourage people to import what they need with `import {thing} from 'frontend-js-web'` (that's the short answer; there is a longer one).

**Comment by jbalsas** [comment]
Just for reference, and since yuilibrary.com is no more 😢 

**[publish](https://github.com/liferay/yui3/blob/master/src/event-custom/js/event-target.js#L494-L496)**

> Creates a new custom event of the specified type.  If a custom event by that name already exists, it will not be re-created.  In either case the custom event is returned.

So that's deep YUI event system. Nothing we want to worry about now. 

As for the rest, @wincent put it very clearly... those takes might be the ones worth documenting 😉

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments did not make it over to the transferred issue (https://github.com/liferay/liferay-frontend-projects/issues/340).

Oh well, going to close this anyway because I want to clean this whole repo of issues before requesting that it be archived.
