### ISSUE TITLE
Document aui:input and aui:validator

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#218]
One of the most used features in DXP are `aui:input` and `aui:validator`.

Both tags are massively used and contain many hidden features like:
- Multiple input types
- Model Hints
- Default Validations
- Custom Validations
- ...

The goal of this question is to document all the different features supported by these 2 tags and how they interact with each other.

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments did not make it over to the transferred issue (https://github.com/liferay/liferay-frontend-projects/issues/341).

Oh well, going to close this anyway because I want to clean this whole repo of issues before requesting that it be archived.
