### ISSUE TITLE
Standardize line breaks on functions with complex arguments

### ISSUE THREAD

**Issue by markocikos** [liferay/liferay-frontend-guidelines#26]
There are two typical ways of breaking lines, and I've seen both used:

1. Break and indent only on curly brackets, i.e. functions or objects. I believe this is more common globally.
1. Break with new line and indent after open bracket, break with new line after comma. This is consistent with Liferay backend.

Example of 1:
```
foo (arg1, {
    arg2key: arg2value
});
```

Example of 2:
```
foo (
    arg1, 
    {
        arg2key: arg2value
    }
);
```

We should pick one and apply it everywhere.

**Comment by jbalsas** [comment]
Hey @markocikos, this should be handled by prettier now, so it will be consistent across our code. The heuristics are more complex than never/always, because it takes line width (80chars) into account.

You can play with possible outputs at https://prettier.io/playground

Closing for now.

/cc @wincent, in case there's something here you might want to add or consider for the future 😉

**Comment by wincent** [comment]
> handled by prettier

I think that's a pretty good default starting point for anything related to formatting. Any deviations from that — we know there will be some, such as some things requested by Brian, for example — will require a pretty strong rationale in their favor because they'll require us to maintain a layer of infrastructure on top of Prettier.
