### ISSUE TITLE
Standarize JSDoc formatting

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-guidelines#47]
Prettier does not apply any concrete format to jsdocs. It would be nice to have some linting for:

- Force/disallow new lines between jsdoc tags (add new line after @param? Add new line after description?).
- Prefer some tags over others (ex. @return instead of @returns).
- Describe which tags we must use in order to document components (do/dont add descriptions, etc).
- Force adding `@review` tag to every jsdoc (maybe?).

**Comment by wincent** [comment]
Seems reasonable to enforce some basic things, although I am hopeful that with an [eventual hypothetical move towards TypeScript](https://github.com/liferay/liferay-frontend-guidelines/issues/37) we'll rely much less heavily on JSDoc for param and return types (because the names of the parameters + the types should be largely self-documenting), which means that most  JSDoc will be just a brief "human-readable description".

**Comment by p2kmgcl** [comment]
That makes sense, but I was thinking specifically about liferay-portal, where (for now) we need to write JS, and having typings with jsdocs is useful.

Personally I do prefer not writing params/return descriptions and only adding method/function/class descriptions where they are needed with a short phrase (or a longer explanation if it's relevant).

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments did not make it over to the transferred issue (https://github.com/liferay/liferay-frontend-projects/issues/350).

Oh well, going to close this anyway because I want to clean this whole repo of issues before requesting that it be archived.
