### ISSUE TITLE
Update react-dnd version

### ISSUE THREAD

**Issue by oliv-yu** [liferay/liferay-frontend-guidelines#64]
It looks like there is already a conversation about which Drag&Drop strategy to use (https://github.com/liferay/liferay-frontend-guidelines/issues/39), but since there was an error with the 7.0.2 version of react-dnd, is it possible to have it updated to 7.4.5 for now?

Related Slack thread: https://liferay.slack.com/archives/C03CAD9EF/p1563170226067100?thread_ts=1562712571.054600&cid=C03CAD9EF

**Comment by thektan** [comment]
@jbalsas @wincent Can we move forward with this change to version `7.4.5` since the bump in version contains [a bug fix with createRef in components](https://github.com/react-dnd/react-dnd/issues/998)? A new module (`portal-search-ranking-web` that will soon be merged in `liferay-portal-ee/master-private` requires the update.

If we get the go-ahead, I can: 
- send a PR to master for updating the version in [`frontend-react-js-web` ](url)
- update any other references to the older version of `react-dnd` in master
- send a PR to the `liferay-npm-tools` repo's [`liferay-npm-bundler-preset-liferay-dev`](https://github.com/liferay/liferay-npm-tools/blob/9b26b5719fb4968f5426a3da34ac5b6839e2ca37/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L87).

**Comment by wincent** [comment]
That sounds like a good plan to me @thektan. Technically, I don't think we *need* to update the preset because it uses a sufficiently loose (`>=`) version range, but @jbalsas will correct me if I am wrong about that. Just saying, because updating the preset is a bit of a chore (you have to update it, publish it, then update liferay-npm-scripts to depend on it etc).

**Comment by jbalsas** [comment]
Hey @thektan, I think @wincent is correct.

I've created https://issues.liferay.com/browse/LPS-99879 so we can take care of updating the version in portal and documenting this properly.

Thanks!

**Comment by wincent** [comment]
I sent an upstream PR for this (https://github.com/brianchandotcom/liferay-portal/pull/77075), and we don't need to commit any changes for this here, so I'm going to close this one.
