### ISSUE TITLE
ESlint rule for avoiding usage of FormData methods, except for `append`

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-guidelines#75]
Folks, would be a good idea include a rule to check if dev is currently using unsupported IE11 methods for Form Data or maybe for other features with partial support for IE11?

/cc @jbalsas @brunobasto

**Comment by wincent** [comment]
In an ideal world we'd have robust polyfills for IE in place that allow us to more or less program in the same way no matter which browser we're talking about. But, in the event that we can't do that for some reason, a lint sounds like a good idea. @diegonvs: do you know of any specific reasons why polyfills couldn't help us out here?

(I'd also hope that we don't have to directly manipulate `FormData` all that often; ideally we'd encapsulate that kind of "raw" manipulation closer to our core network APIs. But I haven't done an audit to see what our current usages are.)

**Comment by diegonvs** [comment]
Hey @wincent,

A polyfill is another great solution but in `FormData` specific case we can use `objectToFormData` Liferay's API in conjunction with some cautions, like avoiding `set` or another IE11-non-supported method. I bet for a rule for these use cases with partial support for avoiding a dependency.

**Comment by wincent** [comment]
I'm a bit worried that takes us in a direction we don't want to go. Would you rather live in a world where:

- You can basically pretend that your code is always running in an modern, evergreen browser like Chrome, Firefox or Safari. You can use anything you find on MDN. You never need to go to caniuse.com.

**Or**, a world in which:

- We have fences and guardrails — which we have to maintain — to prevent you from getting hurt by the limitations of one legacy browser; lints tell you not to use standard APIs and instead use custom Liferay ones.

I think we pretty clearly prefer the former (that's why we use Babel at all, for example). We were trying to take another step towards this in [LPS-95425](https://issues.liferay.com/browse/LPS-95425). And if `FormData` isn't working well, that just suggests to me a gap in our polyfilling strategy and not that we should adopt a different strategy. (That's why I asked if there was any specific challenge with addressing this via a polyfill... maybe there are? I don't know. 🤷‍♂ )

**Comment by jbalsas** [comment]
Yeah, I think we agree here. The problem was caused because we moved to `core-js`, which... as its own name actually indicates, only polyfills js core language features. `FormData`, being a whatwg spec is not in there, same as `fetch`.

We need to re-add one good polyfill for form-data and keep this in mind in the future.

I can take care of this next week.

We can close here, probably since I also see a +1 from @bryceosterhaus
